services:
  - type: web
    name: my-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: DATABASE_URL
        fromGroup: DATABASE_URL